programming_languages = [
    ["python"], ["javascript"], ["java"], ["c#"], ["c++"], ["ruby"], ["php"], ["swift"], ["go"], ["r"],
    ["kotlin"], ["perl"], ["scala"], ["objective-c"], ["rust"], ["dart"], ["typescript"], ["shell"],
    ["sql"], ["html"], ["css"], ["matlab"], ["lua"], ["haskell"], ["fortran"], ["f#"], ["elixir"],
    ["clojure"], ["visual", "basic"], ["bash"], ["vhdl"], ["verilog"], ["groovy"], ["ada"], ["tcl"],
    ["erlang"], ["julia"], ["assembly"], ["cobol"], ["pascal"], ["prolog"], ["pl", "sql"], ["sas"],
    ["racket"], ["xojo"], ["abap"], ["delphi"], ["labview"], ["simulink"], ["powershell"]
]

general_skills = [
    ["communication"], ["leadership"], ["problem-solving"], ["teamwork"], ["adaptability"],
    ["time", "management"], ["critical", "thinking"], ["creativity"], ["conflict", "resolution"],
    ["decision", "making"], ["emotional", "intelligence"], ["negotiation"], ["organization"],
    ["work", "ethic"], ["interpersonal", "skills"], ["project", "management"], ["attention", "to", "detail"],
    ["collaboration"], ["presentation", "skills"], ["active", "listening"], ["networking"],
    ["public", "speaking"], ["mentoring"], ["coaching"], ["delegation"], ["stress", "management"],
    ["customer", "service"], ["empathy"], ["strategic", "thinking"], ["agility"], ["initiative"],
    ["self-motivation"], ["cultural", "awareness"], ["multitasking"], ["innovation"],
    ["process", "improvement"], ["relationship", "management"], ["change", "management"],
    ["risk", "management"], ["technical", "writing"], ["research"], ["flexibility"], ["resilience"],
    ["accountability"], ["dependability"], ["data-driven", "decision", "making"], ["persuasion"],
    ["self-discipline"], ["supervision"], ["teaching"]
]

data_science_skills = [
    ["machine", "learning"], ["deep", "learning"], ["natural", "language", "processing"], ["data", "analysis"],
    ["data", "visualization"], ["statistical", "analysis"], ["python"], ["r"], ["sql"], ["tensorflow"], ["keras"],
    ["pytorch"], ["scikit-learn"], ["pandas"], ["numpy"], ["matplotlib"], ["seaborn"], ["big", "data"],
    ["apache", "spark"], ["hadoop"], ["data", "wrangling"], ["data", "mining"], ["data", "cleaning"], ["data", "modeling"],
    ["predictive", "modeling"], ["supervised", "learning"], ["unsupervised", "learning"], ["reinforcement", "learning"],
    ["classification"], ["regression"], ["clustering"], ["dimensionality", "reduction"], ["time", "series", "analysis"],
    ["anomaly", "detection"], ["feature", "engineering"], ["bayesian", "inference"], ["a/b", "testing"], ["nosql"],
    ["cloud", "computing"], ["amazon", "web", "services"], ["microsoft", "azure"], ["google", "cloud", "platform"],
    ["data", "pipelines"], ["etl"], ["apis"], ["business", "intelligence"], ["tableau"], ["power", "bi"], ["d3.js"], ["plotly"],
    ["dash"], ["data", "ethics"], ["model", "deployment"], ["mlops"], ["devops"], ["automation"], ["jupyter", "notebooks"],
    ["mathematics"], ["statistics"], ["linear", "algebra"], ["calculus"], ["probability"], ["hypothesis", "testing"],
    ["optimization"], ["genetic", "algorithms"], ["random", "forests"], ["support", "vector", "machines"], ["xgboost"],
    ["lightgbm"], ["catboost"], ["principal", "component", "analysis"], ["text", "mining"], ["image", "processing"],
    ["computer", "vision"], ["convolutional", "neural", "networks"], ["recurrent", "neural", "network"],
    ["autoencoders"], ["gans"], ["bayesian", "networks"], ["data", "governance"], ["data", "security"], ["data", "privacy"],
    ["ai", "ethics"], ["docker"], ["kubernetes"], ["version", "control"], ["jenkins"], ["sql", "server"], ["oracle"],
    ["mongodb"], ["cassandra"], ["elasticsearch"], ["data", "lakes"], ["data", "warehousing"], ["snowflake"], ["bigquery"],
    ["hdfs"], ["airflow"], ["apache", "kafka"], ["presto"], ["hive"], ["pig"]
]

blockchain_skills = [
    ["blockchain", "architecture"], ["cryptography"], ["smart", "contracts"], ["ethereum"], ["solidity"], ["hyperledger"],
    ["bitcoin"], ["ripple"], ["consensus", "algorithms"], ["proof", "of", "work"], ["proof", "of", "stake"], ["dapps"], ["distributed", "ledgers"],
    ["tokenization"], ["decentralization"], ["blockchain", "security"], ["hashing", "algorithms"], ["wallet", "development"],
    ["ico"], ["sto"], ["defi"], ["nfts"], ["chaincode"], ["blockchain", "integration"], ["peer", "to", "peer", "networks"],
    ["public", "key", "infrastructure"], ["elliptic", "curve", "cryptography"], ["sha-256"], ["merkle", "trees"],
    ["hyperledger", "fabric"], ["hyperledger", "sawtooth"], ["stellar"], ["eos"], ["cardano"], ["polkadot"], ["truffle"],
    ["ganache"], ["web3.js"], ["blockchain", "api"], ["corda"], ["cosmos"], ["quorum"], ["zilliqa"], ["blockchain", "consensus"],
    ["atomic", "swaps"], ["sharding"], ["blockchain", "testing"], ["blockchain", "analytics"], ["decentralized", "finance"],
    ["interoperability"], ["sidechains"], ["blockchain", "as", "a", "service"], ["zero-knowledge", "proofs"], ["smart", "contract", "auditing"],
    ["gas", "optimization"], ["blockchain", "governance"], ["oracles"], ["cross-chain", "solutions"], ["dao"], ["supply", "chain", "management"],
    ["enterprise", "blockchain"], ["private", "blockchain"], ["public", "blockchain"], ["permissioned", "blockchain"],
    ["ico", "regulations"], ["blockchain", "development", "frameworks"], ["token", "standards"], ["ethereum", "2"], ["defi", "protocols"],
    ["decentralized", "exchanges"], ["metamask"], ["ganache", "cli"], ["ipfs"], ["blockchain", "scalability"], ["governance", "tokens"],
    ["erc", "20"], ["erc", "721"], ["trc", "20"], ["smart", "contract", "security"], ["layer", "2", "solutions"], ["interchain", "communication"],
    ["identity", "management"], ["cryptographic", "tokens"], ["blockchain", "platforms"], ["blockchain", "mining"],
    ["digital", "signatures"], ["multi-signature", "wallets"], ["blockchain", "api"], ["consensus", "mechanisms"], ["solana"], ["avalanche"], 
    ["blockchain", "analytics", "tools"], ["trustless", "systems"], ["blockchain", "adoption"], ["liquidity", "mining"]
]

web_dev_skills = [
    ["html"], ["css"], ["javascript"], ["typescript"], ["react"], ["vue.js"], ["angular"], ["node.js"], ["express.js"],
    ["next.js"], ["nuxt.js"], ["jquery"], ["ajax"], ["bootstrap"], ["sass"], ["less"], ["tailwind", "css"], ["webpack"], ["babel"],
    ["restful", "apis"], ["graphql"], ["json"], ["xml"], ["http"], ["https"], ["websockets"], ["responsive", "design"], ["seo"],
    ["cross-browser", "compatibility"], ["progressive", "web", "apps"], ["single", "page", "applications"],
    ["server-side", "rendering"], ["git"], ["github"], ["version", "control"], ["ci"], ["cd"], ["agile"], ["scrum"],
    ["devops"], ["docker"], ["kubernetes"], ["nginx"], ["apache"], ["cloudflare"], ["web", "security"], ["ssl"], ["tls"],
    ["oauth"], ["jwt"], ["web", "authentication"], ["cors"], ["content", "management", "systems"], ["wordpress"],
    ["shopify"], ["magento"], ["drupal"], ["ui", "design"], ["ux", "design"], ["ui"], ["ux"], ["wireframing"], ["prototyping"], ["figma"], ["adobe", "xd"],
    ["sketch"], ["web", "performance", "optimization"], ["lazy", "loading"], ["code", "splitting"], ["minification"],
    ["service", "workers"], ["localstorage"], ["sessionstorage"], ["indexeddb"], ["browser", "compatibility"], ["accessibility"],
    ["testing"], ["unit", "testing"], ["integration", "testing"], ["jest"], ["mocha"], ["cypress"], ["selenium"],
    ["api", "testing"], ["postman"], ["authentication"], ["authorization"], ["oauth", "2"], ["json", "web", "tokens"],
    ["microservices"], ["web", "assembly"], ["graphql", "subscriptions"], ["real-time", "data"], ["serverless", "architecture"],
    ["aws", "lambda"], ["google", "cloud", "functions"], ["azure", "functions"], ["cdn"], ["server", "side", "caching"],
    ["database", "optimization"], ["sql"], ["nosql"], ["mongodb"], ["firebase"], ["postgresql"], ["sqlite"]
]



app_dev_skills = [
    ["android", "development"], ["ios", "development"], ["swift"], ["kotlin"], ["java"], ["react", "native"], ["flutter"],
    ["dart"], ["objective-c"], ["xcode"], ["android", "studio"], ["mobile", "ui", "design"], ["cross-platform", "development"],
    ["rest", "apis"], ["graphql", "apis"], ["sqlite"], ["firebase"], ["room", "database"], ["realm"], ["coredata"], ["mvvm"],
    ["mvc"], ["mvp"], ["app", "performance", "optimization"], ["push", "notifications"], ["in-app", "purchases"], ["app", "store", "optimization"],
    ["automated", "testing"], ["unit", "testing"], ["espresso"], ["junit"], ["xctest"], ["cloud", "functions"], ["apple", "pay", "integration"],
    ["google", "play", "billing"], ["security", "best", "practices"], ["oauth"], ["fingerprint", "authentication"], ["face", "id"],
    ["mobile", "app", "deployment"], ["crash", "analytics"], ["memory", "management"], ["multithreading"], ["coroutines"], ["data", "caching"],
    ["bluetooth", "integration"], ["location", "services"], ["maps", "integration"], ["augmented", "reality"], ["virtual", "reality"],
    ["wearable", "app", "development"], ["internet", "of", "things"], ["mobile", "payments"], ["sdk", "development"], ["api", "integration"],
    ["ui", "testing"], ["mocking"], ["dependency", "injection"], ["recyclerview"], ["listview"], ["material", "design"], ["gesture", "recognition"],
    ["localization"], ["game", "development"], ["unity"], ["unreal", "engine"], ["app", "monetization"], ["admob"], ["firebase", "analytics"],
    ["mobile", "a/b", "testing"], ["prototyping"], ["ux", "research"], ["mobile", "accessibility"], ["hybrid", "app", "development"],
    ["cordova"], ["ionic"], ["phonegap"], ["app", "analytics"], ["user", "engagement", "metrics"], ["react", "navigation"],
    ["navigation", "components"], ["google", "play", "console"], ["apple", "developer", "console"], ["figma"], ["sketch"], ["zeplin"], ["framer"],
    ["mobile", "devops"], ["bitrise"], ["fastlane"], ["continuous", "integration"], ["continuous", "delivery"]
]



abbreviations_dict = {"ml": "machine learning",
    "dl": "deep learning",
    "nlp": "natural language processing",
    "ai": "artificial intelligence",
    "sql": "structured query language",
    "etl": "extract, transform, load",
    "bi": "business intelligence",
    "aws": "amazon web services",
    "gcp": "google cloud platform",
    "mlops": "machine learning operations",
    "cnns": "convolutional neural networks",
    "rnns": "recurrent neural networks",
    "pca": "principal component analysis",
    "svm": "support vector machines",
    "gans": "generative adversarial networks",
    "apis": "application programming interfaces",
    "nosql": "non-relational database query language",
    "hdfs": "hadoop distributed file system",
    "rpa": "robotic process automation",
    "xgboost": "extreme gradient boosting",
    "pki": "public key infrastructure",
    "ecc": "elliptic curve cryptography",
    "ico": "initial coin offering",
    "sto": "security token offering",
    "dapps": "decentralized applications",
    "defi": "decentralized finance",
    "nfts": "non-fungible tokens",
    "dao": "decentralized autonomous organization",
    "baas": "blockchain-as-a-service",
    "erc-20": "ethereum request for comments 20",
    "erc-721": "ethereum request for comments 721",
    "trc-20": "tron request for comments 20",
    "dex": "decentralized exchange",
    "web3": "web 3.0",
    "sha": "secure hash algorithm",
    "gas": "transaction fees on ethereum",
    "p2p": "peer-to-peer",
    "tx": "transaction",
    "zkp": "zero-knowledge proof",
    "tx fee": "transaction fee",
    "html": "hypertext markup language",
    "css": "cascading style sheets",
    "js": "javascript",
    "ts": "typescript",
    "pwa": "progressive web apps",
    "spa": "single page applications",
    "ssr": "server-side rendering",
    "ajax": "asynchronous javascript and xml",
    "rest": "representational state transfer",
    "api": "application programming interface",
    "json": "javascript object notation",
    "cms": "content management system",
    "ux": "user experience",
    "ui": "user interface",
    "ci/cd": "continuous integration/continuous deployment",
    "ssl": "secure sockets layer",
    "tls": "transport layer security",
    "jwt": "json web token",
    "oauth": "open authorization",
    "devops": "development and operations",
    "cdn": "content delivery network",
    "sql": "structured query language",
    "nosql": "not only sql",
    "db": "database",
    "aws": "amazon web services",
    "gcp": "google cloud platform",
    "nginx": "engine x",
    "d3": "data-driven documents",
     "sdk": "software development kit",
    "rest": "representational state transfer",
    "api": "application programming interface",
    "ar": "augmented reality",
    "vr": "virtual reality",
    "aso": "app store optimization",
    "iot": "internet of things",
    "cv": "computer vision",
    "mvvm": "model-view-viewmodel",
    "mvc": "model-view-controller",
    "mvp": "model-view-presenter",
    "sql": "structured query language",
    "oauth": "open authorization",
    "junit": "java unit testing",
    "xctest": "testing framework for ios",
    "adb": "android debug bridge",
    "ci/cd": "continuous integration/continuous deployment",
    "firebase": "mobile and web application development platform",
    "ui": "user interface",
    "ux": "user experience",
    "cron": "command run on",
    "bitrise": "continuous integration and delivery platform for mobile apps",
    "firebase analytics": "google's app analytics tool"
}

# List of degree-related keywords to search for
degree_keywords = [
    ["degree"], ["diploma"],  ["bachelor's"],  ["master's"],  ["phd"],["ug"],  ["pg"], ["b.tech"],
    ["b.sc"], ["bca"],["b.e"],  ["under", "graduate"], ["post", "graduate"],  ["mca"],
    ["computer", "science"],["software", "engineering"], ["bachelor", "of", "computer", "applications"],["bachelor", "of", "technology"],
    ["bachelor", "of", "science"], ["intermediate"], ["high", "school"]
]
not_change_keyword=["b.e","b.tech",
    "b.sc","bachelor's", "master's","a/b","vue.js", "node.js", "express.js",
    "next.js", "nuxt.js","web3.js","c#", "c++"]
exprenice_keyword=[["entry","level"],["freshers"],["internship"],["internships"]
,["fresher"],["Recent", "graduate"],["experience"]
,["newcomer"]]